rvm:
- 1.9.3
- 2.0.0
after_success: echo after_succes
before_deploy: echo before_deploy
after_deploy: echo after_deploy
deploy:
  provider: heroku
  api_key:
    secure: QFTQdTIhiOzbYfBcY0dNKQ17VqCiBp08n5Gd8ZhzrGflehzdll/wr2313LA9MYnfjBxZhWmSg0iHG/mqdj8NlC6oa3f6YNU8RNlIxFd1toOokgk/8RE/7qW5ks8FsPbfH5+hcN2UNy8sF6yMJTddTRwj6+0VjrDj4X1BJ/JecAM=
  app: travis-chat
  on:
    repo: rkh/travis-chat
    tags: true
